[package]
name = "rust_advent_of_code_2022_day03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib.workspace = true
itertools.workspace = true
